config/routes.rb
#Econodin::Application.routes.draw do
Rails.application.routes.draw do

  get 'investments/index'

	resources :lancamento, :only => [:create, :update, :destroy, :show]
	get "lancamentos", :controller => "lancamento", :action => "list"
	patch "lancamento/:id/finalizar", :controller => "lancamento", :action => "finalizar"

	resource :saldoatual, :controller => "saldo_atual", :only => [:update, :show]

	get "dashboard2" => "dashboard#index2"
	get "dashboard" => "dashboard#index"
	root "home#index"
	devise_for :users
end

app/controllers/home_controller.rb
#encoding: UTF-8
class HomeController < ApplicationController
	layout "application_logout"

  def index
  	
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
= stylesheet_link_tag "home", media: "all", "data-turbolinks-track" => true

div class="jumbotron title"
  div class="container"
    div class="row"
      div class="col-lg-2 col-lg-offset-8 col-md-2 col-md-offset-8 col-sm-2 col-sm-offset-7 col-xs-2 col-xs-offset-4"
        button class="btn btn-primary btn-lg pull-right" type="button" data-toggle="modal" data-target="#modal-login" Entrar
      div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"
        =link_to 'Registre-se', new_user_registration_path, :class=>"btn btn-success btn-lg"
    div class="row"
      div class="col-md-6"
        h1 Econodin
        p Seu controle financeiro fácil e descomplicado
      div class="col-md-6"

section class="section1"
  div class="container"
    h1 class="text-center" Simples e gratuito
    div class="row"
      div class="col-md-12"

hr

footer class="footer-style"
  div class="container"
    div class="row"
      div class="col-md-6"
        h5 Econodin - Contrrole Financeiro Pessoal


div id="modal-login" class="modal fade" role="dialog" tabindex="-1"
	div class="modal-dialog modal-sm"
		div class="modal-content"
			div class="modal-header"
				button type="button" class="close" data-dismiss="modal" aria-label="Close"
					span aria-hidden="true" &times;
				h4
					strong id="titulo" Entrar

			div class="modal-body fields-form-lanc"
				div class="login-card"
					= form_tag session_path(:user), :id => "new_user", :class => "new_user form-signin", :role => "form" do
						span class="reauth-email"
						input type="email" id="user_email" name="user[email]" class="form-control" placeholder="Email" required="" autofocus=""
						input type="password" id="user_password" name="user[password]" class="form-control" placeholder="Password" required=""
						div class="checkbox"
							div class="checkbox"
								label
									input type="checkbox" Lembre de mim
						button class="btn btn-primary btn-block btn-lg btn-signin" type="submit" Entra
					a href="#" class="forgot-password" Forgot your password?