config/routes.rb
#Econodin::Application.routes.draw do
Rails.application.routes.draw do

  get 'investments/index'

	resources :lancamento, :only => [:create, :update, :destroy, :show]
	get "lancamentos", :controller => "lancamento", :action => "list"
	patch "lancamento/:id/finalizar", :controller => "lancamento", :action => "finalizar"

	resource :saldoatual, :controller => "saldo_atual", :only => [:update, :show]

	get "dashboard2" => "dashboard#index2"
	get "dashboard" => "dashboard#index"
	root "home#index"
	devise_for :users
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert-box radius #{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert]
      = content_tag :div, msg
      a.close[href="#"]
        | ×

app/views/layouts/_navigation.html.slim
/nav class=""
/	= link_to 'Dashbord', dashboard_path
/	a href="#" Lançamentos
/	a href="#" Relatórios
/	= link_to 'Investimentos', investments_index_path
/	= link_to 'Sair', destroy_user_session_path, :method => :delete


nav class="navbar navbar-default custom-header"
	div class="container-fluid"
		div class="navbar-header"
			a class="navbar-brand navbar-link" href="/dashboard" Econodin
			button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"
				span class="sr-only" Toggle navigation
				span class="icon-bar"
				span class="icon-bar"
				span class="icon-bar"

		div class="collapse navbar-collapse" id="navbar-collapse"
			ul class="nav navbar-nav links"
				li role="presentation"
					a href="#" Dashboard
				li role="presentation"
					a href="#" Lançamentos
				li role="presentation"
					a href="#" Relatórios
				li role="presentation"
					a href="#" class="custom-navbar" Investimentos
			ul class="nav navbar-nav navbar-right"
				li class="dropdown"
					a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#"
						span class="caret"
						i class="glyphicon glyphicon-user dropdown-image"
					ul class="dropdown-menu dropdown-menu-right" role="menu"
						li role="presentation" class="active"
							= link_to 'Sair', destroy_user_session_path, :method => :delete

app/views/layouts/_navigation_links.html.slim
= link_to 'Dashbord', dashboard_path

app/views/layouts/application.html.slim
doctype html
html lang="pt-br" ng-app="econodin"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Econodin'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Econodin'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags

  body ng-controller="DashboardController as dashboard" ng-init="busca_saldo_atual()"
    header class=""
      == render 'layouts/navigation'
    main[role="main" ng-view=""]
      == render 'layouts/messages'
      == yield
    footer class="footer-style"
      div class="container"
        div class="row"
          div class="col-md-6"
            h5 Econodin - Contrrole Financeiro Pessoal

app/views/layouts/application_logout.html.slim
doctype html
html lang="pt-br"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Econodin'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Econodin'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
    main[role="main"]
      == render 'layouts/messages'
      == yield